apiVersion: v1
kind: Service
metadata:
  name: oncall-prober-service
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9081"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: oncall-prober
  ports:
    - protocol: TCP
      port: 9081
      targetPort: 9081
