apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9101"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: my-app
    app.kubernetes.io/name: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: my-app
    - protocol: TCP
      port: 9101
      targetPort: 9101
      name: metrics